#!/usr/bin/env python3
"""
Roundtrip 回归测试: .rpy -> .xlsx -> .rpy, 验证内容一致。
双击打开 → 交互菜单
命令行: python test_roundtrip.py [test.rpy ...]
"""

import sys
import os
import tempfile
from pathlib import Path

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from rpy_to_excel import parse_rpy, write_excel
from excel_to_rpy import convert_excel_to_rpy, _find_game_dir, _fix_working_directory


def normalize(text: str) -> list:
    lines = []
    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("# Generated by"):
            continue
        if stripped.startswith("# 源文件:"):
            continue
        lines.append(line.rstrip())
    return lines


def run_roundtrip(rpy_path: str) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        xlsx_path = tmp_dir / "test.xlsx"
        rpy_out = tmp_dir / "test.rpy"
        rows = parse_rpy(rpy_path)
        write_excel(rows, str(xlsx_path))
        convert_excel_to_rpy(str(xlsx_path), str(rpy_out), manage_defines=False)
        return rpy_out.read_text(encoding="utf-8")


def _game_script_path() -> str:
    game_dir = _find_game_dir()
    return str(game_dir / "script.rpy") if game_dir else ""


def test_file(rpy_path: str) -> bool:
    print(f"\n{'='*60}")
    print(f"Test: {os.path.basename(rpy_path)}")

    with open(rpy_path, "r", encoding="utf-8-sig") as f:
        original = f.read()

    try:
        roundtrip = run_roundtrip(rpy_path)
    except Exception as e:
        print(f"  FAIL: {e}")
        return False

    orig_lines = normalize(original)
    rt_lines = normalize(roundtrip)

    if orig_lines == rt_lines:
        print(f"  PASS: {len(orig_lines)} lines match")
        return True

    import difflib
    diff = list(difflib.unified_diff(
        orig_lines, rt_lines,
        fromfile="original", tofile="roundtrip",
        lineterm=""
    ))
    print(f"  FAIL: {len(orig_lines)} vs {len(rt_lines)} lines differ")
    for d in diff[:20]:
        prefix = d[0] if d else " "
        content = d[1:] if len(d) > 1 else ""
        if prefix == "-":
            print(f"  DEL: {content[:100]}")
        elif prefix == "+":
            print(f"  ADD: {content[:100]}")
    return False


def _strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        s = s[1:-1]
    return s


def _interactive_test():
    print("\n" + "-" * 40)
    path = input("请输入 .rpy 文件路径（可直接拖拽文件到此处）：\n> ").strip()
    path = _strip_quotes(path)
    if not path:
        print("[ERROR] 未输入路径，返回主菜单。")
        return
    if not os.path.isfile(path):
        print(f"[ERROR] 文件不存在：{path}")
        return
    if not path.lower().endswith(".rpy"):
        print(f"[ERROR] 不是 .rpy 文件。")
        return
    test_file(path)


def interactive_mode():
    while True:
        print()
        print("=" * 40)
        print("  Roundtrip 回归测试")
        print("=" * 40)
        print("  1. 测试自带样本 (test_roundtrip.rpy)")
        print("  2. 测试游戏脚本 (game/script.rpy)")
        print("  3. 同时测试两者")
        print("  4. 测试其他 .rpy 文件")
        print("  5. 退出")
        print("-" * 40)
        choice = input("请选择 (1/2/3/4/5)：").strip()

        if choice == "1":
            test_file(os.path.join(SCRIPT_DIR, "test_roundtrip.rpy"))
            input("\n按 Enter 键继续...")
        elif choice == "2":
            game = _game_script_path()
            if os.path.isfile(game):
                test_file(game)
            else:
                print(f"[ERROR] 文件不存在：{game}")
            input("\n按 Enter 键继续...")
        elif choice == "3":
            passed = 0
            total = 0
            for p in [os.path.join(SCRIPT_DIR, "test_roundtrip.rpy"),
                      _game_script_path()]:
                if os.path.isfile(p):
                    total += 1
                    if test_file(p):
                        passed += 1
            print(f"\nResults: {passed}/{total} passed")
            input("\n按 Enter 键继续...")
        elif choice == "4":
            _interactive_test()
            input("\n按 Enter 键继续...")
        elif choice == "5":
            print("再见！")
            break
        else:
            print("[ERROR] 无效选择。")


def main():
    _fix_working_directory()

    if len(sys.argv) > 1:
        passed = 0
        failed = 0
        for path in sys.argv[1:]:
            path = _strip_quotes(path)
            if os.path.isfile(path):
                if test_file(path):
                    passed += 1
                else:
                    failed += 1
            else:
                print(f"[ERROR] File not found: {path}")
                failed += 1
        print(f"\n{'='*60}")
        print(f"Results: {passed} passed, {failed} failed")
        if failed:
            sys.exit(1)
        return

    try:
        interactive_mode()
    except KeyboardInterrupt:
        print("\n\n再见！")
    except Exception as e:
        print(f"\n[ERROR] {e}")
        input("\n按 Enter 键退出...")


if __name__ == "__main__":
    main()
